name: Affected Apps and Libs

on:
  workflow_call:
    inputs:
      NX_BASE:
        required: true
        type: string
      NX_HEAD:
        required: true
        type: string

jobs:
  affected:
    runs-on: ubuntu-latest
    steps:
      - name: ðŸš€ Lint Apps
        run: npm run nx affected:lint --base=${{ inputs.NX_BASE }} --head=${{ inputs.NX_HEAD  }}  --parallel --maxParallel=3

      - name: ðŸš€ Test Apps
        run: npm run nx affected:test --passWithNoTests --base=${{ inputs.NX_BASE }} --head=${{ inputs.NX_HEAD  }}  --parallel --maxParallel=3

      - name: ðŸš€ e2e Apps
        run: npm run nx affected:e2e --base=${{ inputs.NX_BASE }} --head=${{ inputs.NX_HEAD  }}  --parallel --maxParallel=3

      - name: ðŸš€ Build Apps
        run: npm run nx affected:build --base=${{ inputs.NX_BASE }} --head=${{ inputs.NX_HEAD  }}  --parallel --maxParallel=3